//@version=5
indicator(title='Trend Strength Directional', shorttitle='TSD', timeframe='')

//// Indicators
// Blue Wave
n1 = input.int(10, 'Channel Length', group='Wave Length')
n2 = input.int(21, 'Average Length', group='Wave Length')
over_bought_level = input.int(53, 'Over Bought Level', group='Levels')
over_sold_level = input.int(-53, 'Over Sold Level', group='Levels')
ap = hlc3
esa = ta.ema(ap, n1)
d = ta.ema(math.abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ta.ema(ci, n2)
wt1 = tci
wt2 = ta.sma(wt1, 4)

// MFI
mfi_upper = math.sum(volume * (ta.change(hlc3) <= 0 ? 0 : hlc3), 58)
mfi_lower = math.sum(volume * (ta.change(hlc3) >= 0 ? 0 : hlc3), 58)
_mfi_rsi(mfi_upper, mfi_lower) =>
    if mfi_lower == 0
        100
    if mfi_upper == 0
        0
    100.0 - 100.0 / (1.0 + mfi_upper / mfi_lower)
mf = _mfi_rsi(mfi_upper, mfi_lower)
mfi = (mf - 50) * 3

//// Plots
mfi_color = mfi > 0 ? #4CAF50 : #FF5252
dot_color = wt1 < wt2 ? #FF0000 : #4CAF50
hline(over_bought_level, linestyle=hline.style_dotted, color=color.white, title='Upper Level')
hline(over_sold_level, linestyle=hline.style_dotted, color=color.white, title='Lower Level')
plot(wt1, style=plot.style_area, color=color.new(#5EB4FF, 0), title='Light Wave')
plot(wt2, style=plot.style_area, color=color.new(#131722, 22), title='Dark Wave')
plot(mfi, 'MFI Area', style=plot.style_area, color=color.new(mfi_color, 60), linewidth=2, display=display.none)
plot(mfi, 'MFI Line', style=plot.style_line, color=mfi_color, linewidth=2, display=display.none)
plot(ta.crossunder(wt1, wt2) or ta.crossover(wt1, wt2) ? wt2 : na, title='Dots', style=plot.style_circles, color=color.new(dot_color, 20), linewidth=3)
bgcolor(color.new(#000000, 80))

